/* Single source of truth for the site. Edit here; index.html and the chart render from it.
   Dates are decimal years (2020.5 = mid-2020). Use `date: null` to keep a project off the chart. */

const ROLES = [
  { id: 'hansen', company: 'Hansen Technologies', place: 'Pune', title: 'Analyst, Data Engineering & Platforms',
    start: 2018.58, end: 2020.83, range: 'Aug 2018 – Nov 2020', projectIds: [],
    points: ['Data-driven insights for telecom product optimisation across Latin America and Australia.',
             'Built reporting frameworks supporting strategic decisions for the telecom product portfolio.'] },
  { id: 'pharmeasy', company: 'PharmEasy', place: 'Bangalore · E-commerce', title: 'Business Data Analyst (Data Science)',
    start: 2020.83, end: 2022.0, range: 'Nov 2020 – Jan 2022', projectIds: ['forecast', 'echo'],
    points: ['Ensemble demand forecasting (SARIMA, ARIMA, weighted moving average) lifted accuracy from 30–40% to 50–70%.',
             'ECHO: probabilistic SKU model that flagged hard-to-procure products, cutting order deletions by ~0.2–0.3% of PAN-India orders.',
             'Linked central, weekly and local purchase workflows to ease the procurement team’s workload.'] },
  { id: 'niyo', company: 'Niyo Solutions', place: 'Bangalore · Fintech', title: 'Senior Data Scientist',
    start: 2022.0, end: 2023.21, range: 'Jan 2022 – Mar 2023', projectIds: ['lending', 'mix', 'vkyc', 'ft'],
    points: ['Lending propensity ensembles on SageMaker: +20% disbursement rate at 79.5% recall on imbalanced data.',
             'Linear-programming source-mix optimiser: 5–7% weekly user growth and $20–30K monthly savings.',
             'XGBoost-driven VKYC demand filter lifted approvals from 20% to 24% in week one.',
             'Funds-transfer activation model (~500K users, ~88% accuracy) raised activation from 40% to 48%.'] },
  { id: 'twid', company: 'Twid Pay', place: 'Bangalore · Fintech', title: 'Lead Data Scientist',
    start: 2023.42, end: 2026.1, range: 'Jun 2023 – Feb 2026', projectIds: ['twid'],
    points: ['Affluence scoring: +8–9% conversion for new users and +16% uplift for repeat customers (F1 0.78, 84% recall).',
             'RFM models drove $280K (INR 2.5 cr) monthly GMV impact, validated with A/B tests.',
             'Cut API response time 64% (700ms → 250ms) with pre-screening confidence scoring.',
             'End-to-end MLOps on S3, Airflow and MLflow; graph-based merchant recommendations.'] },
  { id: 'bicycle', company: 'Bicycle.ai', place: 'Bangalore', title: 'Principal Data Scientist',
    start: 2026.1, end: null, range: 'Feb 2026 – Present', projectIds: ['bicycle'],
    points: ['Five-agent Claude forecasting pipeline with a RAG layer, ~675K daily orders, zero hard-coded schema.',
             'Skill-driven Detect→Explain RFM migration engine for ~89,590 customers, deployed multi-tenant on AWS Lambda and ECS.',
             'Config-driven churn platform (XGBoost, LightGBM, SHAP, LIME) with DoWhy/EconML causal drivers, ~34M events.'] }
];

const NOW = 2026.77; // chart right edge (Oct 2026)

const MILESTONES = [
  { id: 'be', label: 'B.E. graduation', date: 2018.4, side: 'right',
    text: 'Bachelor of Engineering in Computer Science, MIT College of Engineering, Pune.' },
  { id: 'vil', label: 'VIL CodeFest winner', date: 2020.12, side: 'right',
    text: 'Winner of the Vodafone-Idea Hackathon (VIL CodeFest), February 2020.' },
  { id: 'rak', label: 'Rakathon top 100', date: 2023.7, side: 'right',
    text: 'Top 100 finalist at Rakathon by Rakuten with an LLM-based project, September 2023.' }
];

/* row: vertical slot inside the projects lane; side: which way the label runs from the dot */
const CHART_PROJECTS = [
  { id: 'p-churn', label: 'Customer-Churn', date: 2019.77, row: 0, side: 'right',
    text: 'Customer churn analysis with machine learning (Jupyter). Oct 2019.', url: 'https://github.com/pratik9696/Customer-Churn' },
  { id: 'p-opt', label: 'StockOptions', date: 2020.03, row: 1, side: 'right',
    text: 'Basics of options strategies in Python (Jupyter). Jan 2020.', url: 'https://github.com/pratik9696/StockOptions' },
  { id: 'p-genai', label: 'GenAI', date: 2025.21, row: 0, side: 'right',
    text: 'GenAI experiments in Python. Mar 2025.', url: 'https://github.com/pratik9696/GenAI' },
  { id: 'p-tel', label: 'ThinkEasyLabs site', date: 2026.25, row: 1, side: 'left',
    text: 'Next.js + Tailwind marketing site for ThinkEasyLabs, live on Vercel. Apr 2026.', url: 'https://github.com/pratik9696/tel-website' },
  { id: 'p-ezq', label: 'EZquote', date: 2026.35, row: 0, side: 'left',
    text: 'Cost Sheet Assistant: reads an RFQ, Excel sheet or WhatsApp voice note and pre-fills a ~80-field ERP costing form for human approval.', anchor: 'ezquote' },
  { id: 'p-sb', label: 'Second Brain', date: 2026.45, row: 2, side: 'left',
    text: 'Always-on AI business analyst on a hybrid Claude + open-weight stack, ~70% cheaper than pure Claude. In progress.', anchor: 'second-brain' },
  { id: 'p-rag', label: 'Self-Correcting RAG', date: 2026.68, row: 3, side: 'left',
    text: 'RAG agent with a learned router and a validated groundedness grader. Sep 2026.', url: 'https://github.com/pratik9696/dataworkz' },
  { id: 'p-ims', label: 'Iceano IMS', date: 2026.74, row: 4, side: 'left',
    text: 'Inventory management system for Iceano on Cloudflare Pages, Functions and D1. Sep 2026.', url: 'https://github.com/pratik9696/icecream-inventory' }
];

/* cat: ai | app | prod | ml.   status drives the badge colour.
   Order matters: the first six show by default, the rest sit behind "Show all". */
const PROJECTS = [
  { id: 'ezquote', name: 'EZquote · Cost Sheet Assistant', tag: 'Agentic AI · ERP · Think Easy Labs', cat: ['ai', 'app'], status: 'Live prototype',
    repo: null,
    kpi: { v: '~80', l: 'costing-form fields pre-filled per quote' },
    blurb: 'Turns a quotation into a conversation. The assistant reads an RFQ, an Excel sheet or a WhatsApp voice note, then pre-fills the corrugated-box costing form so marketing reviews a number instead of typing eighty of them.',
    problem: 'A client requirement, however it arrives, funnels through one person who knows both the ERP and the costing rules, typing dimensions, ply-wise material, printing, wastage, logistics and margin into roughly eighty fields. Typically one person per plant can do it correctly.',
    archTitle: 'Intake → ERP pipeline',
    arch: ['RFQ · Excel · voice note', 'AI extraction → canonical schema', 'Ask, don’t guess (one WhatsApp question)', 'Deterministic costing engine', 'Human approves → ERP'],
    facts: ['Man-hours: 15–30+ min of typing per quote becomes review and edit, flagged fields first',
            'Accuracy: numbers come from versioned rate cards and a deterministic engine, not free-hand entry',
            'Delay: a draft is ready within minutes of the RFQ, sheet or voice note arriving',
            'Decentralisation: any field or regional staff can submit by chat; ERP access stays limited to review'],
    stack: ['Vision extraction', 'Speech-to-text', 'LLM', 'Deterministic costing engine', 'WhatsApp', 'ERP'],
    note: 'The LLM never writes to the ERP. It resolves language and narrates the result; every number comes from the costing engine, and a human approval tap is the only step with write access.' },
  { id: 'rag', name: 'Self-Correcting RAG', tag: 'LLM · RAG · Evals', cat: ['ai'], status: 'Public repo',
    repo: 'https://github.com/pratik9696/dataworkz',
    kpi: { v: '1.000', l: 'key-fact accuracy with self-correction' },
    blurb: 'A question-answering agent over a 70-document corpus. A classical ML router picks the retrieval strategy per query, a hybrid dense+sparse retriever fetches evidence, a local LLM answers with citations, and a validated groundedness grader decides whether to retry with a different strategy.',
    arch: ['Router (logistic regression)', 'Hybrid retrieval (RRF)', 'Generate with citations', 'Groundedness self-check', 'Retry with escalated strategy'],
    facts: ['Router held-out accuracy 0.933', 'Retrieval recall@5 0.947', 'Key-fact accuracy 0.947 → 1.000 with self-correction', 'Runs on CPU, no API keys; reproduced with zero diffs'],
    stack: ['Python', 'Ollama (llama3.1:8b)', 'scikit-learn', 'Hybrid RRF retrieval'],
    note: 'The README is candid that the router adds little recall on this corpus and that multi-hop retrieval is the weakest part.' },
  { id: 'bicycle', name: 'Bicycle.ai agentic engines', tag: 'Production · Agentic AI', cat: ['ai', 'prod'], status: 'Production',
    repo: null,
    kpi: { v: '~34M', l: 'events validated, churn platform' },
    blurb: 'Three production platforms where classical ML meets agents: a five-agent demand-forecasting pipeline (Prophet, SARIMA, LSTM, Croston/SBA) with RAG grounding, a skill-driven RFM migration engine, and a config-driven churn platform with causal ML (DoWhy, EconML, Double ML, X-Learner).',
    archTitle: 'Five-agent forecasting pipeline',
    arch: ['Data Analyzer', 'Feasibility Classifier', 'Dataset Builder', 'Model Trainer', 'Results Analyst'],
    facts: ['~675K daily orders forecast', '~89,590 customers across 10 RFM segments', '~34M events, new vertical = one YAML file'],
    stack: ['Claude Agent SDK', 'XGBoost / LightGBM', 'SHAP / LIME', 'AWS Lambda + ECS'],
    note: 'Proprietary work; described from the résumé.' },
  { id: 'second-brain', name: 'Second Brain', tag: 'Agentic AI · Cost-optimised', cat: ['ai'], status: 'In progress',
    repo: null,
    kpi: { v: '~70%', l: 'cheaper than pure-Claude setups' },
    blurb: 'An analyst that keeps working while the business owner runs the business. It uses a hybrid of Claude and open-weight models to give better visibility into the business at a fraction of the cost.',
    arch: [],
    facts: ['~70% cheaper than pure-Claude setups', 'Evals and harness work in progress', 'Hybrid Claude + open-weight routing'],
    stack: ['Claude', 'Open-weight LLMs', 'Evals', 'Agent harness'],
    note: 'Repository is not public yet.' },
  { id: 'iceano', name: 'Iceano IMS', tag: 'Full-stack · Inventory', cat: ['app'], status: 'Public repo',
    repo: 'https://github.com/pratik9696/icecream-inventory',
    kpi: { v: 'Edge', l: 'serverless on Cloudflare' },
    blurb: 'Inventory management system for Iceano, an ice-cream business. A lightweight web front end backed by Cloudflare Pages Functions and a D1 database, with writes mirrored to the existing Google Sheet so its native dashboard keeps working.',
    arch: ['Web front end', 'Pages Functions API', 'D1 database', 'Google Sheets mirror'],
    facts: ['Serverless on Cloudflare Pages + D1', 'Schema migrations and migration scripts', 'Backwards-compatible Google Sheets mirror'],
    stack: ['JavaScript', 'Cloudflare Pages Functions', 'D1 (SQLite)', 'Wrangler'] },
  { id: 'tel', name: 'ThinkEasyLabs landing page', tag: 'Web', cat: ['app'], status: 'Live',
    repo: 'https://github.com/pratik9696/tel-website', live: 'https://tel-website-one.vercel.app',
    kpi: { v: 'Live', l: 'deployed on Vercel' },
    blurb: 'Production marketing site for ThinkEasyLabs, which builds AI solutions across manufacturing, healthcare, BFSI, retail and logistics using open-source and Claude models.',
    arch: [],
    facts: ['Next.js App Router', 'Tailwind CSS', 'SEO metadata, smooth scroll, Vercel deploy'],
    stack: ['Next.js', 'TypeScript', 'Tailwind', 'Vercel'] },

  /* ---- earlier roles ---- */
  { id: 'twid', name: 'Affluence scoring & RFM revenue engine', tag: 'Twid Pay · Fintech', cat: ['ml', 'prod'], status: 'Production',
    repo: null,
    kpi: { v: '$280K', l: 'monthly GMV impact (INR 2.5 cr)' },
    blurb: 'An ensemble affluence-scoring system for targeted marketing, plus RFM models on transaction data that drove monthly GMV, all shipped with an end-to-end MLOps pipeline and validated through A/B tests in a regulated fintech environment.',
    archTitle: 'MLOps pipeline',
    arch: ['Transaction data on S3', 'Airflow orchestration', 'Model training + MLflow tracking', 'Low-latency scoring API', 'A/B test validation'],
    facts: ['+8–9% conversion for new users, +16% uplift for repeat customers', 'F1 0.78 and 84% recall in user segmentation', 'API response time down 64%, 700ms → 250ms, via pre-screening confidence scoring',
            'RFM models with 0.5% MDE at 0.05 significance', 'Graph-based merchant recommendations from transaction patterns'],
    stack: ['Python', 'Ensembles', 'AWS S3', 'Airflow', 'MLflow'],
    note: 'Proprietary work; described from the résumé.' },
  { id: 'mix', name: 'Marketing source-mix optimisation', tag: 'Niyo · Linear programming', cat: ['ml', 'prod'], status: 'Production',
    repo: null,
    kpi: { v: '5–7%', l: 'weekly user-base growth' },
    blurb: 'Gave the marketing team a direction on where to spend, keeping KPIs such as D7 load and activation in control. A linear-programming model (OpenSolver) set the right split of acquired users across Google, Facebook, affiliates and other sources, with CAC and budget distributed accordingly.',
    archTitle: 'Self-serve refresh pipeline',
    arch: ['Upload config CSV to S3', 'AWS Lambda trigger', 'SageMaker LP optimiser', 'Refreshed QuickSight dashboard'],
    facts: ['5–7% week-on-week user-base growth', 'Non-performing sources removed up front, saving about $20–30K a month', 'Stakeholders were non-technical: uploading a config CSV refreshes spend, CAC and user counts in QuickSight', 'Described in the résumé notes as one of the most impactful projects in the org'],
    stack: ['Linear programming', 'OpenSolver', 'AWS S3', 'SageMaker', 'Lambda', 'QuickSight'] },
  { id: 'lending', name: 'Lending propensity model', tag: 'Niyo · Imbalanced ML', cat: ['ml', 'prod'], status: 'Production',
    repo: null,
    kpi: { v: '+20%', l: 'improvement in disbursement rate' },
    blurb: 'Identifies the customers most likely to buy a loan from the bank, using behavioural, transactional and demographic features on a heavily imbalanced dataset. An ensemble method produces the propensity, served as API endpoints from AWS SageMaker.',
    archTitle: 'Scoring flow',
    arch: ['Behavioural + transactional + demographic data', 'Ensemble propensity model', 'SageMaker API endpoint', 'High-propensity customers filtered'],
    facts: ['20% improvement in disbursement rate', '79.5% recall, strong given few disbursement samples', 'Multi-source user profile for an approval-likelihood score if the user opts for a loan'],
    stack: ['Python', 'Ensemble methods', 'AWS SageMaker', 'API endpoints'] },
  { id: 'vkyc', name: 'VKYC demand filtering', tag: 'Niyo · XGBoost', cat: ['ml', 'prod'], status: 'Production',
    repo: null,
    kpi: { v: '20→24%', l: 'approval rate in week one' },
    blurb: 'VKYC slots were limited, so only customers likely to get a banker’s approval were offered video KYC over the traditional route. XGBoost drove feature engineering and selection, and segment rules were turned into a live filtering criterion.',
    archTitle: 'Filter logic',
    arch: ['Onboarding data', 'XGBoost feature selection', 'Segment rules', 'Real-time filter in production'],
    facts: ['Approvals rose from 20% to 24% within the first week of deployment', 'Target: beat the 60% market benchmark in the following weeks', 'Rules generated per segment so decisions are made on the go'],
    stack: ['XGBoost', 'Feature selection', 'Rule extraction'] },
  { id: 'ft', name: 'Funds-transfer activation & churn', tag: 'Niyo · Ensemble forecasting', cat: ['ml', 'prod'], status: 'Production',
    repo: null,
    kpi: { v: '40→48%', l: 'activation rate, above industry benchmarks' },
    blurb: 'Predicts which prime customers are most likely to make a funds transfer (NEFT, RTGS, IFT, IMPS). A random forest and XGBoost ensemble trained on about 500K users’ transactions, with a rolling three-month forecast used to plan campaigns.',
    arch: [],
    facts: ['~500K users’ transaction data', 'Random forest + XGBoost ensemble, ~88% accuracy, precision around 64%', 'Month-on-month forecast for the next three months, used to plan campaigns', 'Retraining in production designed in'],
    stack: ['Random forest', 'XGBoost', 'Forecasting', 'Retraining'] },
  { id: 'forecast', name: 'Demand forecasting', tag: 'PharmEasy · Time series', cat: ['ml', 'prod'], status: 'Production',
    repo: null,
    kpi: { v: '50–70%', l: 'accuracy, up from 30–40%' },
    blurb: 'An ensemble of SARIMA, ARIMA and weighted moving average for weekly forecasts replaced a weighted-moving-average-only model, improving procurement planning through COVID-era demand and traffic surges.',
    arch: [],
    facts: ['Accuracy 50–70% versus 30–40% before', 'Modelled seasonality, COVID demand surges and traffic surges', 'More SKUs landed in the ±10% MAPE bucket', 'Connected central, weekly and local purchase workflows to ease procurement workload'],
    stack: ['SARIMA', 'ARIMA', 'Weighted moving average', 'Ensembling'] },
  { id: 'echo', name: 'ECHO · SKU availability prediction', tag: 'PharmEasy · Probabilistic model', cat: ['ml', 'prod'], status: 'Production',
    repo: null,
    kpi: { v: '0.2–0.3%', l: 'fewer deleted PAN-India orders' },
    blurb: 'Predicts which SKUs will fall into the just-in-time category because stock is unavailable in warehouses across India, based on how past orders for each SKU performed. Hard-to-procure products can then be marked out of stock on the platform up front.',
    arch: [],
    facts: ['Probabilistic model per SKU built from order history', 'Hard-to-procure SKUs flagged and marked out of stock', 'Order deletions reduced by ~0.2–0.3% of PAN-India orders'],
    stack: ['Probabilistic modelling', 'Order analytics'] }
];

const MORE_REPOS = [
  { name: 'Customer-Churn', desc: 'Customer churn analysis using machine learning', year: 2019, url: 'https://github.com/pratik9696/Customer-Churn' },
  { name: 'StockOptions', desc: 'Basics of options strategy using Python', year: 2020, url: 'https://github.com/pratik9696/StockOptions' },
  { name: 'GenAI', desc: 'GenAI experiments', year: 2025, url: 'https://github.com/pratik9696/GenAI' },
  { name: 'SEM_Bicycle_DS', desc: 'Bicycle data science assessment', year: 2025, url: 'https://github.com/pratik9696/SEM_Bicycle_DS' }
];

const SKILLS = [
  ['LLM & Agentic AI', ['Claude Agent SDK', 'Multi-agent pipelines', 'MCP tool-calling', 'RAG', 'Skill-driven automation', 'Vertex AI', 'Prompt engineering']],
  ['ML & Deep Learning', ['XGBoost', 'LightGBM', 'Random Forest', 'PyTorch', 'TensorFlow', 'scikit-learn', 'HuggingFace']],
  ['Causal & Explainability', ['DoWhy', 'EconML', 'Double ML', 'X-Learner', 'Uplift modelling', 'SHAP', 'LIME']],
  ['Forecasting & Analytics', ['Prophet', 'SARIMA', 'LSTM', 'Croston/SBA', 'A/B testing', 'RFM', 'Linear programming', 'Statistical modelling']],
  ['Cloud & MLOps', ['AWS SageMaker', 'Bedrock', 'Lambda', 'ECS', 'S3', 'QuickSight', 'Airflow', 'MLflow', 'Kafka', 'CI/CD for ML']],
  ['Languages & Tools', ['Python', 'SQL', 'PySpark', 'Git', 'Jupyter', 'Tableau']]
];
